### ISSUE TITLE
unacceptable syntax

### ISSUE THREAD

**Issue by vaeious** [sferaggio/deezer-flac-download#3]
there's an issue when trying to download a song or album if the artist name or song name contains characters that windows explorer won't accept, like question marks or asterisks, and the operation will abort or return an error

**Comment by dnk8n** [comment]
I also noticed that, I made a small PR which solves some of my cases, you might need to extend for your own. I don't have time to properly sanitize the paths.

Maybe it can help you.

**Comment by vaeious** [comment]
oh cool! I ended up using ChatGPT to analyse the relevant parts of the code and add in the sanitisation blocks (because I can't program haha), and we went back and forth until all the desired modifications were in place and functional. thankyou for offering the PR though!
